Jastarnia:
  lat: 54.695
  lon: 18.678

BridgeTown:
  lat: 13.105
  lon: -59.613

Fortelaza:
  lat: -3.732
  lon: -38.527

Pissouri:
  lat: 34.664
  lon: 32.706

LeMorne:
  lat: -20.445
  lon: 57.328

