my:
  cities:
    -
      lat: 54.695
      lon: 18.678

    -
      lat: 13.105
      lon: -59.613

    -
      lat: -3.732
      lon: -38.527

    -
      lat: 34.664
      lon: 32.706

    -
      lat: -20.445
      lon: 57.328

