spring:
    cache:
        jcache:
            config: classpath:ehcache.xml
forecastResource:
    weatherApiUrl: https://api.weatherbit.io/v2.0/forecast/daily
app:
    cities:
    -   lat: 54.695
        lon: 18.678
    -   lat: 13.105
        lon: -59.613
    -   lat: -3.732
        lon: -38.527
    -   lat: 34.664
        lon: 32.706
    -   lat: -20.445
        lon: 57.328

management:
    health:
      circuitbreakers:
        enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
        health:
          show-details: always

resilience4j.circuitbreaker:
    instances:
        forecast:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10